[package]
name = "bricks"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.0"

[lints]
workspace = true

[workspace]
members = ["type_process_builder", "qrios_api_process_runner", "qrios_api_axum_server", "qrios_api_process_entry", "qrios_api_reqwest_client", "xtask"]

[dependencies]
type_process_builder = { path = "type_process_builder" , features = ["docs"]}
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
typenum = { version = "1.0" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
inline-always = "allow" # I hope the frunk guys done the measurements
missing-errors-doc = "allow"
default-trait-access = "allow" # Denying it causes repetitive code in phantom data initialisation
type-complexity = "allow" # sorry for complex types
