[package]
name = "process_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.2" , features = ["macros"]}
#phf_codegen = "0.11.2"
#serde = "1.0"